(() => {
  const endpoint='https://n8n-production-21ba.up.railway.app/webhook/tamien-calendar-sep25-2026-approvals';
  const legacyKey='tamien-review-sep25-2026-approvals-v1', controls=new Map(), state={};
  let ready=false, loading=false, migrating=false;
  let legacy={};try{legacy=JSON.parse(localStorage.getItem(legacyKey)||'{}')}catch(_){}
  const summary=document.createElement('p');summary.className='muted';summary.setAttribute('role','status');summary.textContent='Loading shared approvals…';
  (document.querySelector('.intro')||document.querySelector('header')||document.querySelector('main')).append(summary);
  function accept(row){if(row&&controls.has(row.post)&&(!state[row.post]||Number(row.id)>=Number(state[row.post].id)))state[row.post]=row;}
  function paint(post){const c=controls.get(post),r=state[post];if(c.busy)return;c.check.checked=r?.approved===true;c.check.disabled=!ready;c.status.textContent=r?(r.approved?'Approved':'Reopened')+' · '+new Date(r.updatedAt).toLocaleString():ready?'Awaiting approval':'Loading…';const badge=c.host.querySelector('.badge');if(badge&&badge.dataset.posted!=='true')badge.textContent=r?.approved?'Approved':'Pending approval';}
  async function request(options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(endpoint,{cache:'no-store',...options,signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Approval could not be saved.');return d;}finally{clearTimeout(timer)}}
  async function save(post,value,migrate=false){const c=controls.get(post);c.busy=true;c.check.disabled=true;c.status.textContent='Saving…';try{const d=await request({method:'POST',body:new URLSearchParams({post,approved:String(value),migrate:String(migrate),requestId:crypto.randomUUID()})});if(!d.approval)throw Error('Approval was not confirmed.');accept(d.approval);delete legacy[post];try{localStorage.setItem(legacyKey,JSON.stringify(legacy))}catch(_){}return true;}catch(e){c.error='Could not confirm approval. Refresh and try again.';return false;}finally{c.busy=false;paint(post);if(c.error){c.status.textContent=c.error;c.error=null}}}
  async function importLegacy(){if(migrating)return;migrating=true;try{for(const [post,v]of Object.entries(legacy)){if(v!==true||!controls.has(post))continue;if(state[post]){delete legacy[post];continue;}await save(post,true,true);}try{localStorage.setItem(legacyKey,JSON.stringify(legacy))}catch(_){}}finally{migrating=false}}
  async function refresh(){if(loading)return;loading=true;try{const d=await request();if(!d.approvals||typeof d.approvals!=='object')throw Error('Invalid response');Object.values(d.approvals).forEach(accept);ready=true;for(const post of controls.keys())paint(post);summary.textContent='Approvals are shared · updates refresh automatically.';await importLegacy();}catch(_){summary.textContent='Shared approvals could not refresh. Please check your connection and try again.';}finally{loading=false}}
  for(const p of window.REVIEW_DATA.posts){const host=document.getElementById(p.id);if(!host)continue;let check=host.querySelector('.approved input');let wrap;if(check){wrap=check.parentElement;}else{wrap=document.createElement('label');wrap.className='approved';check=document.createElement('input');check.type='checkbox';wrap.append(check,document.createTextNode(' Approved'));(host.querySelector('.postBody')||host).prepend(wrap);}check.disabled=true;check.setAttribute('aria-label','Approved: '+p.id);const status=document.createElement('small');status.style.cssText='display:block;font-weight:400;font-size:12px;margin-top:4px';status.setAttribute('role','status');wrap.append(status);controls.set(p.id,{check,status,host,busy:false});check.onchange=()=>save(p.id,check.checked);}
  const retry=document.createElement('button');retry.type='button';retry.className='textbutton';retry.textContent='Refresh approvals';retry.onclick=refresh;summary.after(retry);
  refresh();setInterval(()=>{if(!document.hidden)refresh()},10000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
})();
