(() => {
  const endpoint=window.COMMENTS_ENDPOINT;
  if (!endpoint) return;
  const boards=new Map();
  let comments=[];
  function element(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;}
  function draw(){for(const [post,b] of boards){b.list.replaceChildren();const rows=comments.filter(c=>c.post===post);if(!rows.length)b.list.append(element('p','comment-empty','No comments yet.'));for(const c of rows){const article=element('article','comment-item');const date=new Date(c.createdAt);article.append(element('span','comment-date',Number.isNaN(date.valueOf())?'':date.toLocaleString()),element('p','',c.message));b.list.append(article);}}}
  async function refresh(){const r=await fetch(endpoint,{cache:'no-store'});if(!r.ok)throw Error('Comments could not load. Please try again.');const data=await r.json();if(!Array.isArray(data.comments))throw Error('Comments could not load.');comments=data.comments;draw();}
  for(const p of window.REVIEW_DATA.posts){const host=document.getElementById(p.id);if(!host)continue;const area=element('section','comment-board');area.setAttribute('aria-label','Comments for '+p.id);area.append(element('h3','','Comments'));const list=element('div','comment-list');list.append(element('p','comment-empty','Loading comments…'));const form=element('form','comment-form');const messageLabel=element('label','','Comment'),message=element('textarea');message.name='message';message.required=true;message.maxLength=2000;message.rows=3;message.placeholder='Leave feedback on this post…';messageLabel.append(message);const trap=element('input','comment-trap');trap.name='website';trap.tabIndex=-1;trap.autocomplete='off';trap.setAttribute('aria-hidden','true');const send=element('button','comment-send','Post comment');send.type='submit';const status=element('p','comment-status');status.setAttribute('role','status');const retry=element('button','textbutton','Refresh comments');retry.type='button';retry.onclick=async()=>{try{await refresh();status.textContent='Comments refreshed.'}catch(e){status.textContent=e.message}};form.append(messageLabel,trap,send);area.append(list,form,element('p','muted','Shared with everyone who has this review link. No sign-in required.'),status,retry);(host.querySelector('.postBody')||host).append(area);boards.set(p.id,{list,status});let requestId=null,lastPayload='';form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const text=message.value.trim();if(!text){status.textContent='Please enter your comment.';return;}const payload=text;if(payload!==lastPayload||!requestId){requestId=crypto.randomUUID();lastPayload=payload;}send.disabled=true;status.textContent='Saving…';try{const r=await fetch(endpoint,{method:'POST',body:new URLSearchParams({post:p.id,message:text,requestId,website:trap.value})});const data=await r.json();if(!r.ok||!data.comment)throw Error(data.error||'Could not save. Your comment is still here; please try again.');if(!comments.some(x=>x.id===data.comment.id))comments.push(data.comment);draw();message.value='';requestId=null;status.textContent='Comment saved and shared.';}catch(e){status.textContent=e.message||'Could not save. Please try again.';}finally{send.disabled=false}};
  }
  refresh().catch(e=>{for(const b of boards.values()){b.list.replaceChildren();b.status.textContent=e.message;}});
})();
